"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import {
  ArrowLeft, ArrowRight, BadgeCheck, Box, Check, ChevronDown, ChevronLeft,
  ChevronRight, CircleDollarSign, Copy, CreditCard, Edit3, Gauge,
  Grid2X2, Headphones, ImagePlus, LayoutDashboard,
  Menu, Package, PackageCheck, Plus, Search, ShieldCheck,
  ShoppingCart, SlidersHorizontal, Tag, Trash2, Truck, UploadCloud,
  Warehouse, X
} from "lucide-react";
import { FaWhatsapp } from "react-icons/fa6";
import { fetchMainCategories, fetchStoreProducts, subscribeToCatalog, type MainCategory } from "../lib/store-data";
import { deleteProduct, saveProduct, type ProductInput } from "../lib/store-admin";
import { supabase } from "../lib/supabase";

export type Product = {
  id: number; name: string; brand: string; category: string; price: number; oldPrice?: number;
  stock: number; image: string; gallery?: string[]; featured?: boolean; isNew?: boolean;
  description: string; specs: Record<string,string>; warranty: string;
  dbId?: string; code?: string; slug?: string; model?: string; minimumStock?: number;
  isActive?: boolean; createdAt?: string;
  images?: Array<{id:string;storagePath:string;url:string;isPrimary:boolean;sortOrder:number}>;
};

export const demoProducts: Product[] = [
  {id:1,name:"PC Gamer Ryzen 5 RTX 4060",brand:"NextLevel",category:"PC gamer",price:7499000,oldPrice:8299000,stock:6,featured:true,image:"https://images.unsplash.com/photo-1587202372634-32705e3bf49c?auto=format&fit=crop&w=900&q=85",description:"Equipo equilibrado para gaming competitivo en 1080p y creación de contenido. Ensamblado y probado por técnicos especializados.",specs:{Procesador:"AMD Ryzen 5 5600","Memoria RAM":"16 GB DDR4 3200 MHz","Almacenamiento":"SSD NVMe 1 TB","Tarjeta gráfica":"GeForce RTX 4060 8 GB","Sistema operativo":"Windows 11 Pro","Potencia":"650 W 80+ Bronze"},warranty:"12 meses"},
  {id:2,name:"PC Gamer Ryzen 7 RTX 4070",brand:"NextLevel",category:"PC gamer",price:12690000,stock:3,featured:true,isNew:true,image:"https://images.unsplash.com/photo-1593640408182-31c70c8268f5?auto=format&fit=crop&w=900&q=85",description:"Potencia de alto nivel para jugar en 1440p, hacer streaming y trabajar con aplicaciones profesionales.",specs:{Procesador:"AMD Ryzen 7 7700","Memoria RAM":"32 GB DDR5","Almacenamiento":"SSD NVMe 2 TB","Tarjeta gráfica":"GeForce RTX 4070 Super","Conectividad":"Wi‑Fi 6 + Bluetooth 5.2","Potencia":"750 W 80+ Gold"},warranty:"18 meses"},
  {id:3,name:"Notebook Lenovo IdeaPad Slim 3",brand:"Lenovo",category:"Notebooks",price:4299000,oldPrice:4699000,stock:9,image:"https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=900&q=85",description:"Notebook liviana y confiable para estudio, oficina y uso diario con excelente autonomía.",specs:{Procesador:"Intel Core i5 12ª Gen","Memoria RAM":"16 GB","Almacenamiento":"SSD 512 GB","Pantalla":"15,6” Full HD","Sistema operativo":"Windows 11 Home","Peso":"1,62 kg"},warranty:"12 meses"},
  {id:4,name:"Notebook ASUS TUF Gaming A15",brand:"ASUS",category:"Notebooks",price:8999000,stock:4,featured:true,isNew:true,image:"https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&w=900&q=85",description:"Notebook gamer robusta con pantalla de alta frecuencia y refrigeración de doble ventilador.",specs:{Procesador:"AMD Ryzen 7 7735HS","Memoria RAM":"16 GB DDR5","Almacenamiento":"SSD 1 TB","Tarjeta gráfica":"RTX 4060 8 GB","Pantalla":"15,6” 144 Hz","Conectividad":"Wi‑Fi 6"},warranty:"12 meses"},
  {id:5,name:"PlayStation 5 Slim 1 TB",brand:"Sony",category:"PlayStation",price:5699000,oldPrice:6099000,stock:7,featured:true,image:"https://images.unsplash.com/photo-1606813907291-d86efa9b94db?auto=format&fit=crop&w=900&q=85",description:"La nueva versión Slim con lector, almacenamiento ultrarrápido y control DualSense.",specs:{Almacenamiento:"SSD 1 TB","Resolución":"Hasta 4K 120 Hz","Conectividad":"Wi‑Fi 6 / Bluetooth 5.1","Incluye":"DualSense + Astro’s Playroom","Dimensiones":"358 × 96 × 216 mm"},warranty:"12 meses"},
  {id:6,name:"Xbox Series X 1 TB",brand:"Microsoft",category:"Xbox",price:5999000,stock:2,image:"https://images.unsplash.com/photo-1621259182978-fbf93132d53d?auto=format&fit=crop&w=900&q=85",description:"La Xbox más potente, con tiempos de carga mínimos y miles de juegos de cuatro generaciones.",specs:{Almacenamiento:"SSD 1 TB","Resolución":"4K nativo","Rendimiento":"Hasta 120 FPS","Conectividad":"HDMI 2.1 / Wi‑Fi","Incluye":"Control inalámbrico"},warranty:"12 meses"},
  {id:7,name:"Nintendo Switch OLED 64 GB",brand:"Nintendo",category:"Nintendo",price:3499000,stock:8,isNew:true,image:"https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?auto=format&fit=crop&w=900&q=85",description:"Consola híbrida con pantalla OLED vibrante de 7 pulgadas, base con LAN y audio mejorado.",specs:{Pantalla:"OLED 7 pulgadas","Almacenamiento":"64 GB","Batería":"4,5 a 9 horas","Conectividad":"Wi‑Fi / Bluetooth","Modos":"TV, sobremesa, portátil"},warranty:"12 meses"},
  {id:8,name:"Monitor Gamer 27” QHD 165 Hz",brand:"AOC",category:"Monitores",price:2899000,oldPrice:3299000,stock:5,image:"https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=900&q=85",description:"Panel rápido y nítido para juegos competitivos con Adaptive Sync y soporte ajustable.",specs:{Panel:"IPS 27 pulgadas","Resolución":"2560 × 1440","Frecuencia":"165 Hz","Respuesta":"1 ms","Conectividad":"DisplayPort / HDMI"},warranty:"24 meses"},
  {id:9,name:"Teclado Mecánico HyperX Alloy",brand:"HyperX",category:"Teclados",price:699000,stock:12,image:"https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=900&q=85",description:"Teclado compacto de estructura sólida, switches mecánicos y retroiluminación RGB.",specs:{Formato:"TKL 87 teclas","Switches":"HyperX Red","Iluminación":"RGB","Conexión":"USB‑C desmontable","Compatibilidad":"PC / PS5 / Xbox"},warranty:"12 meses"},
  {id:10,name:"Mouse Gamer Logitech G502 X",brand:"Logitech",category:"Mouse",price:549000,stock:15,isNew:true,image:"https://images.unsplash.com/photo-1527814050087-3793815479db?auto=format&fit=crop&w=900&q=85",description:"Mouse de alto rendimiento con sensor preciso, diseño ergonómico y botones programables.",specs:{Sensor:"HERO 25K","Resolución":"100–25.600 DPI","Botones":"13 programables","Peso":"89 g","Conexión":"USB"},warranty:"12 meses"},
  {id:11,name:"Auriculares Cloud III Wireless",brand:"HyperX",category:"Auriculares",price:1099000,oldPrice:1249000,stock:6,image:"https://images.unsplash.com/photo-1599669454699-248893623440?auto=format&fit=crop&w=900&q=85",description:"Audio espacial, gran comodidad y batería extendida para sesiones intensas.",specs:{Drivers:"53 mm","Conexión":"2,4 GHz","Autonomía":"Hasta 120 horas","Micrófono":"Desmontable con mute LED","Compatibilidad":"PC / PS5"},warranty:"12 meses"},
  {id:12,name:"SSD NVMe Kingston NV2 1 TB",brand:"Kingston",category:"Almacenamiento",price:599000,stock:20,image:"https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?auto=format&fit=crop&w=900&q=85",description:"Almacenamiento PCIe 4.0 compacto y eficiente para acelerar equipos de escritorio y notebooks.",specs:{Capacidad:"1 TB","Interfaz":"PCIe 4.0 NVMe",Lectura:"Hasta 3.500 MB/s",Formato:"M.2 2280"},warranty:"36 meses"},
  {id:13,name:"Memoria Fury Beast 16 GB DDR5",brand:"Kingston",category:"Memorias RAM",price:549000,stock:18,isNew:true,image:"https://images.unsplash.com/photo-1562976540-1502c2145186?auto=format&fit=crop&w=900&q=85",description:"Módulo DDR5 de alta velocidad con perfil AMD EXPO e Intel XMP.",specs:{Capacidad:"16 GB","Velocidad":"5600 MT/s","Latencia":"CL36","Voltaje":"1,25 V"},warranty:"De por vida"},
  {id:14,name:"GeForce RTX 4070 Super 12 GB",brand:"Gigabyte",category:"Placas de video",price:6999000,stock:3,featured:true,image:"https://images.unsplash.com/photo-1591488320449-011701bb6704?auto=format&fit=crop&w=900&q=85",description:"Gráficos de nueva generación con ray tracing, DLSS 3.5 y sistema de refrigeración de triple ventilador.",specs:{GPU:"NVIDIA RTX 4070 Super","Memoria":"12 GB GDDR6X","Interfaz":"PCIe 4.0","Salidas":"3× DisplayPort, HDMI 2.1","Potencia recomendada":"700 W"},warranty:"24 meses"},
  {id:15,name:"Procesador AMD Ryzen 7 7800X3D",brand:"AMD",category:"Procesadores",price:4199000,oldPrice:4499000,stock:5,image:"https://images.unsplash.com/photo-1555617981-dac3880eac6e?auto=format&fit=crop&w=900&q=85",description:"Procesador gamer de referencia con tecnología 3D V‑Cache para máximo rendimiento.",specs:{Núcleos:"8","Hilos":"16","Frecuencia boost":"5,0 GHz","Caché":"104 MB","Socket":"AM5","TDP":"120 W"},warranty:"36 meses"},
];

const categories = ["Todos","PC gamer","Computadoras de oficina","Notebooks","Monitores","Procesadores","Placas de video","Memorias RAM","Almacenamiento","Fuentes","Gabinetes","Motherboards","Teclados","Mouse","Auriculares","Sillas gamer","Consolas","PlayStation","Xbox","Nintendo","Videojuegos","Accesorios"];
export const gs = (n:number) => `Gs. ${Math.round(n).toLocaleString("es-PY")}`;

export default function Home() {
  const [view,setView]=useState<"shop"|"detail"|"admin">("shop");
  const [detail,setDetail]=useState<Product|null>(null);
  const [query,setQuery]=useState(""); const [category,setCategory]=useState("Todos"); const [brand,setBrand]=useState("Todas");
  const [saleOnly,setSaleOnly]=useState(false); const [stockOnly,setStockOnly]=useState(false); const [sort,setSort]=useState("recent");
  const [min,setMin]=useState(""); const [max,setMax]=useState(""); const [cartOpen,setCartOpen]=useState(false);
  const [cart,setCart]=useState<Record<number,number>>({}); const [menu,setMenu]=useState(false);
  const [admin,setAdmin]=useState(false); const [login,setLogin]=useState({email:"",password:""}); const [loginError,setLoginError]=useState(""); const [loginBusy,setLoginBusy]=useState(false); const [toast,setToast]=useState("");
  const [checkout,setCheckout]=useState(false);
  const [storeProducts,setStoreProducts]=useState<Product[]>(demoProducts);
  const products=storeProducts;
  useEffect(()=>{let active=true;const reload=()=>fetchStoreProducts().then(data=>{if(active)setStoreProducts(data.length?data:demoProducts)}).catch(error=>console.error("Supabase products:",error));reload();const unsubscribe=subscribeToCatalog(reload);return()=>{active=false;unsubscribe()}},[]);
  useEffect(()=>{const timer=setTimeout(()=>{try{setCart(JSON.parse(localStorage.getItem("nlt-cart")||"{}"))}catch{}},0);return()=>clearTimeout(timer)},[]);
  useEffect(()=>{localStorage.setItem("nlt-cart",JSON.stringify(cart))},[cart]);
  const filtered=useMemo(()=>storeProducts.filter(p=>{
    const hay=`${p.name} ${p.brand} ${p.category} ${p.description}`.toLowerCase();
    return (!query||hay.includes(query.toLowerCase()))&&(category==="Todos"||p.category===category)&&(brand==="Todas"||p.brand===brand)&&(!saleOnly||!!p.oldPrice)&&(!stockOnly||p.stock>0)&&(!min||p.price>=+min)&&(!max||p.price<=+max)
  }).sort((a,b)=>sort==="low"?a.price-b.price:sort==="high"?b.price-a.price:sort==="az"?a.name.localeCompare(b.name):(b.createdAt||"").localeCompare(a.createdAt||"")),[storeProducts,query,category,brand,saleOnly,stockOnly,min,max,sort]);
  const cartItems=storeProducts.filter(p=>cart[p.id]).map(p=>({...p,qty:cart[p.id]})); const total=cartItems.reduce((s,p)=>s+p.price*p.qty,0); const count=Object.values(cart).reduce((a,b)=>a+b,0);
  const add=(p:Product)=>{setCart(c=>({...c,[p.id]:Math.min((c[p.id]||0)+1,p.stock)}));setCartOpen(true);setToast(`${p.name} agregado`);setTimeout(()=>setToast(""),1800)};
  const openDetail=(p:Product)=>{setDetail(p);setView("detail");window.scrollTo(0,0)};
  const wa=(p?:Product,customer?:Record<string,string>)=>{const lines=p?[`Hola NextLevel Tech, quiero comprar:`,`• ${p.name} — ${gs(p.price)}`]:["Hola NextLevel Tech, quiero realizar este pedido:",...cartItems.map(x=>`• ${x.name}\n  ${x.qty} × ${gs(x.price)} = ${gs(x.qty*x.price)}`),``,`TOTAL: ${gs(total)}`,``,`Nombre: ${customer?.nombre||""}`,`Teléfono: ${customer?.telefono||""}`,`Ciudad: ${customer?.ciudad||""}`,`Dirección: ${customer?.direccion||""}`,`Referencia: ${customer?.referencia||""}`,`Forma de pago: ${customer?.pago||""}`,`Retiro o delivery: ${customer?.entrega||""}`];window.open(`https://wa.me/595985993848?text=${encodeURIComponent(lines.join("\n"))}`,"_blank")};
  const advisor=()=>{const message=["Hola NextLevel Tech.","","Estoy interesado en recibir asesoramiento para elegir un producto.","","Me gustaría recibir información sobre:","","Computadoras","Notebooks","Componentes","Consolas","Otro:","","Muchas gracias."].join("\n");window.open(`https://wa.me/595985993848?text=${encodeURIComponent(message)}`,"_blank")};
  const verifyAdmin=async(userId:string)=>{const {data,error}=await supabase.from("profiles").select("role").eq("id",userId).single();if(error||data?.role!=="admin"){await supabase.auth.signOut();setAdmin(false);return false}setAdmin(true);return true};
  const handleAdminLogin=async(e:React.FormEvent)=>{e.preventDefault();setLoginBusy(true);setLoginError("");const {data,error}=await supabase.auth.signInWithPassword(login);if(error||!data.user){setLoginError("Correo o contraseña incorrectos.");setLoginBusy(false);return}if(!await verifyAdmin(data.user.id))setLoginError("Este usuario no tiene permisos de administrador.");setLoginBusy(false)};
  useEffect(()=>{supabase.auth.getUser().then(({data})=>{if(data.user)verifyAdmin(data.user.id)});const {data}=supabase.auth.onAuthStateChange((_event,session)=>{if(!session)setAdmin(false)});return()=>data.subscription.unsubscribe()},[]);
  return <div>
    <div className="topline">Envíos a todo Paraguay <span>•</span> Pagá con tarjetas, transferencia o efectivo</div>
    <header><div className="nav">
      <button className="hamb iconBtn" onClick={()=>setMenu(!menu)} aria-label="Abrir menú"><Menu/></button><button className="logo" onClick={()=>setView("shop")}><b>NL</b><span>NextLevel<small>TECH</small></span></button>
      <nav className={menu?"show":""}><button onClick={()=>{setView("shop");setCategory("Todos")}}>Inicio</button><button onClick={()=>{setView("shop");setCategory("Todos");setTimeout(()=>document.getElementById("catalogo")?.scrollIntoView(),20)}}>Productos</button><button onClick={()=>{setView("shop");setSaleOnly(true)}}>Ofertas</button><button onClick={()=>setView("admin")}>Administrar</button></nav>
      <label className="search"><Search/><input aria-label="Buscar productos" value={query} onChange={e=>{setQuery(e.target.value);setView("shop")}} placeholder="Buscar producto, marca o categoría..."/></label>
      <button className="cartBtn" onClick={()=>setCartOpen(true)} aria-label="Abrir carrito"><ShoppingCart/><em>{count}</em></button>
    </div></header>

    {view==="shop"&&<main>
      <section className="hero"><div className="heroCopy"><span className="eyebrow">POTENCIÁ TU PRÓXIMO NIVEL</span><h1>Tecnología que juega <i>en serio.</i></h1><p>Equipos, componentes y periféricos seleccionados para rendir más. Asesoramiento experto y garantía local.</p><div><button className="primary" onClick={()=>document.getElementById("catalogo")?.scrollIntoView()}>Explorar productos <ArrowRight/></button><button className="ghost advisor" onClick={advisor}><FaWhatsapp/> Hablar con un asesor</button></div><div className="trust"><span><BadgeCheck/> Garantía local</span><span><Truck/> Envíos nacionales</span><span><ShieldCheck/> Compra segura</span></div></div><div className="heroImg"><img src="https://images.unsplash.com/photo-1598550476439-6847785fcea6?auto=format&fit=crop&w=1200&q=88" alt="Setup gamer profesional"/><div className="promo"><b>HASTA 15% OFF</b><small>en seleccionados</small></div></div></section>
      <section className="perks"><div><span className="perkIcon"><Truck/></span><p><b>Delivery nacional</b><span>Enviamos a todo Paraguay</span></p></div><div><span className="perkIcon"><CreditCard/></span><p><b>Pagá como prefieras</b><span>Tarjetas, transferencia y efectivo</span></p></div><div><span className="perkIcon"><ShieldCheck/></span><p><b>Compra protegida</b><span>Productos con garantía</span></p></div><div><span className="perkIcon"><Headphones/></span><p><b>Soporte experto</b><span>Te ayudamos a elegir</span></p></div></section>
      <section className="section cats"><div className="sectionHead"><div><span className="eyebrow">EXPLORÁ POR CATEGORÍA</span><h2>Todo para tu setup</h2></div></div><div className="catGrid"><CategoryButton name="PC gamer" image="https://images.unsplash.com/photo-1587202372634-32705e3bf49c?auto=format&fit=crop&w=800&q=88" setCategory={setCategory}/><CategoryButton name="Notebooks" image="https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&w=800&q=88" setCategory={setCategory}/><CategoryButton name="Placas de video" image="https://images.unsplash.com/photo-1591488320449-011701bb6704?auto=format&fit=crop&w=800&q=88" setCategory={setCategory}/><CategoryButton name="Consolas" image="https://images.unsplash.com/photo-1606813907291-d86efa9b94db?auto=format&fit=crop&w=800&q=88" setCategory={setCategory}/><CategoryButton name="Monitores" image="https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=800&q=88" setCategory={setCategory}/><CategoryButton name="Teclados" label="Periféricos" image="https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=88" setCategory={setCategory}/></div></section>
      <section className="section" id="catalogo"><div className="sectionHead"><div><span className="eyebrow">CATÁLOGO NEXTLEVEL</span><h2>Encontrá tu próxima mejora</h2></div><span>{filtered.length} productos</span></div>
        <div className="catalog"><aside className="filterPanel"><div className="filterTitle"><span><SlidersHorizontal/></span><div><b>Filtrar productos</b><small>Refiná tu búsqueda</small></div></div><label>Categoría<div className="selectWrap"><select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select><ChevronDown/></div></label><label>Marca<div className="selectWrap"><select value={brand} onChange={e=>setBrand(e.target.value)}><option>Todas</option>{[...new Set(products.map(p=>p.brand))].map(b=><option key={b}>{b}</option>)}</select><ChevronDown/></div></label><label>Rango de precio<div className="range"><input value={min} onChange={e=>setMin(e.target.value)} placeholder="Precio mínimo" type="number"/><input value={max} onChange={e=>setMax(e.target.value)} placeholder="Precio máximo" type="number"/></div></label><label className="check"><input type="checkbox" checked={saleOnly} onChange={e=>setSaleOnly(e.target.checked)}/><span/> Solo productos en oferta</label><label className="check"><input type="checkbox" checked={stockOnly} onChange={e=>setStockOnly(e.target.checked)}/><span/> Disponibles en stock</label><button className="clear bordered" onClick={()=>{setCategory("Todos");setBrand("Todas");setSaleOnly(false);setStockOnly(false);setMin("");setMax("");setQuery("")}}><X/> Limpiar filtros</button></aside>
        <div className="listing"><div className="toolbar"><div className="chips">{["Todos","PC gamer","Notebooks","PlayStation"].map(c=><button className={category===c?"active":""} onClick={()=>setCategory(c)} key={c}>{c}</button>)}</div><label className="sorter"><span>Ordenar por</span><select value={sort} onChange={e=>setSort(e.target.value)}><option value="recent">Más recientes</option><option value="low">Precio menor a mayor</option><option value="high">Precio mayor a menor</option><option value="az">Nombre A–Z</option></select><ChevronDown/></label></div>{filtered.length?<div className="products">{filtered.map(p=><ProductCard key={p.id} p={p} add={add} open={openDetail}/>)}</div>:<div className="empty"><Search/><b>No encontramos resultados</b><p>Probá con otros términos o limpiá los filtros.</p><button className="primary" onClick={()=>{setQuery("");setCategory("Todos");setBrand("Todas");setSaleOnly(false)}}>Ver todos</button></div>}</div></div>
      </section>
      <section className="brands section"><span className="eyebrow">MARCAS QUE POTENCIAN TU SETUP</span><div>{["ASUS","AMD","NVIDIA","Lenovo","HyperX","Logitech","PlayStation","XBOX"].map(b=><b key={b}>{b}</b>)}</div></section>
      <section className="newsletter section"><div><span className="eyebrow">OFERTAS EXCLUSIVAS</span><h2>Subí de nivel sin pagar de más.</h2><p>Recibí lanzamientos y promociones antes que nadie.</p></div><form onSubmit={e=>{e.preventDefault();setToast("¡Ya estás en la lista!")}}><input type="email" required placeholder="tu@email.com"/><button className="primary">Quiero recibir ofertas</button></form></section>
    </main>}

    {view==="detail"&&detail&&<main className="detail section"><button className="back" onClick={()=>setView("shop")}><ArrowLeft/> Volver al catálogo</button><div className="detailGrid"><div className="gallery"><img src={detail.image} alt={detail.name}/><div>{[detail.image,...products.filter(x=>x.category===detail.category&&x.id!==detail.id).slice(0,2).map(x=>x.image)].map((x,i)=><button key={x}><img src={x} alt={`Vista ${i+1}`}/></button>)}</div></div><div className="info"><span className="stock"><PackageCheck/>{detail.stock>0?`Disponible · ${detail.stock} unidades`:"Agotado"}</span><p className="brand">{detail.brand} / {detail.category}</p><h1>{detail.name}</h1><div className="price">{gs(detail.price)} {detail.oldPrice&&<><del>{gs(detail.oldPrice)}</del><em>-{Math.round((1-detail.price/detail.oldPrice)*100)}%</em></>}</div><p>{detail.description}</p><div className="qty"><span>Cantidad</span><button aria-label="Disminuir">−</button><b>1</b><button aria-label="Aumentar"><Plus/></button></div><button className="primary wide" onClick={()=>add(detail)}><ShoppingCart/> Agregar al carrito</button><button className="wa wide" onClick={()=>wa(detail)}><FaWhatsapp/> Comprar por WhatsApp</button><div className="micro"><span><ShieldCheck/><b>Garantía local</b><small>{detail.warranty}</small></span><span><Truck/><b>Delivery nacional</b><small>A todo Paraguay</small></span><span><CreditCard/><b>Pago flexible</b><small>Consultá opciones</small></span></div></div></div><div className="specBlock"><div><span className="eyebrow">DETALLES DEL PRODUCTO</span><h2>Especificaciones técnicas</h2><p>{detail.description}</p></div><dl>{Object.entries(detail.specs).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></div><div className="sectionHead"><div><span className="eyebrow">TAMBIÉN TE PUEDE INTERESAR</span><h2>Productos relacionados</h2></div></div><div className="products related">{products.filter(p=>p.category===detail.category&&p.id!==detail.id).concat(products.filter(p=>p.id!==detail.id)).slice(0,4).map(p=><ProductCard key={p.id} p={p} add={add} open={openDetail}/>)}</div></main>}

    {view==="admin"&&<main className="admin">{!admin?<div className="login"><div className="logo big"><b>NL</b><span>NextLevel<small>TECH ADMIN</small></span></div><h1>Panel administrativo</h1><p>Acceso exclusivo para administradores.</p><form onSubmit={handleAdminLogin}><label>Correo electrónico<input type="email" required value={login.email} onChange={e=>setLogin({...login,email:e.target.value})} placeholder="administrador@correo.com"/></label><label>Contraseña<input type="password" required value={login.password} onChange={e=>setLogin({...login,password:e.target.value})} placeholder="••••••••"/></label>{loginError&&<p className="loginError">{loginError}</p>}<button className="primary wide" disabled={loginBusy}>{loginBusy?"Verificando...":"Iniciar sesión"}</button><small>La sesión y el rol se validan de forma segura con Supabase.</small></form></div>:<Admin onExit={async()=>{await supabase.auth.signOut();setAdmin(false)}}/>}</main>}

    <aside className={`cart ${cartOpen?"open":""}`}><div className="cartHead"><div><span>MI CARRITO</span><b>{count} {count===1?"producto":"productos"}</b></div><button className="iconBtn" onClick={()=>setCartOpen(false)} aria-label="Cerrar carrito"><X/></button></div><div className="cartBody">{cartItems.length?cartItems.map(p=><div className="cartItem" key={p.id}><img src={p.image} alt=""/><div><b>{p.name}</b><span>{gs(p.price)}</span><div className="step"><button onClick={()=>setCart(c=>({...c,[p.id]:Math.max(1,c[p.id]-1)}))}>−</button><em>{p.qty}</em><button onClick={()=>setCart(c=>({...c,[p.id]:Math.min(p.stock,c[p.id]+1)}))}><Plus/></button><button className="remove" onClick={()=>setCart(c=>{const n={...c};delete n[p.id];return n})}><Trash2/> Eliminar</button></div></div></div>):<div className="emptyCart"><span><ShoppingCart/></span><b>Tu carrito está vacío</b><p>Agregá productos para comenzar.</p></div>}</div>{cartItems.length>0&&<div className="cartFoot"><div><span>Subtotal</span><b>{gs(total)}</b></div><small>El costo de envío se coordina por WhatsApp.</small><button className="wa wide" onClick={()=>setCheckout(true)}><FaWhatsapp/> Finalizar por WhatsApp</button><button className="clear" onClick={()=>setCart({})}><Trash2/> Vaciar carrito</button></div>}</aside>{cartOpen&&<button className="overlay" onClick={()=>setCartOpen(false)}/>}
    {checkout&&<div className="modalWrap"><form className="checkout" onSubmit={e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget).entries()) as Record<string,string>;setCheckout(false);wa(undefined,data)}}><button type="button" className="x" onClick={()=>setCheckout(false)}>×</button><span className="eyebrow">DATOS PARA EL PEDIDO</span><h2>Ya casi está</h2><div className="formGrid"><label>Nombre<input name="nombre" required/></label><label>Teléfono<input name="telefono" required/></label><label>Ciudad<input name="ciudad" required/></label><label>Dirección<input name="direccion" required/></label><label>Referencia<input name="referencia"/></label><label>Forma de pago<select name="pago"><option>Transferencia</option><option>Efectivo</option><option>Tarjeta</option></select></label><label>Entrega<select name="entrega"><option>Delivery</option><option>Retiro del local</option></select></label></div><button className="wa wide">Continuar en WhatsApp</button></form></div>}
    {toast&&<div className="toast"><Check/> {toast}</div>}<button className="floatWa" onClick={advisor} aria-label="WhatsApp"><FaWhatsapp/></button>
    <footer><div className="logo"><b>NL</b><span>NextLevel<small>TECH</small></span></div><p>Tecnología, gaming y potencia para tu próximo nivel.</p><div><b>TIENDA</b><span>Productos</span><span>Ofertas</span><span>Delivery nacional</span></div><div><b>CONTACTO</b><span>+595 985 993 848</span><span>Asunción, Paraguay</span><span>Lun–Sáb · 08:00 a 18:00</span></div><small>© 2026 NextLevel Tech · Creado por PixenWeb</small></footer>
  </div>
}

function CategoryButton({name,label,image}:{name:string,label?:string,image:string,setCategory:(v:string)=>void}){const slug=(label||name).toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/\s+/g,"-");return <button className="categoryCard" onClick={()=>location.href=`/categoria/${slug}`}><span className="categoryMedia"><img src={image} alt={label||name}/></span><span className="categoryContent"><b>{label||name}</b><em>Ver productos <ArrowRight/></em></span></button>}

function ProductCard({p,add,open}:{p:Product,add:(p:Product)=>void,open:(p:Product)=>void}){return <article className="product"><div className="pic">{p.oldPrice&&<span className="badge">-{Math.round((1-p.price/p.oldPrice)*100)}%</span>}{p.isNew&&<span className="badge new">NUEVO</span>}<img src={p.image} alt={p.name}/><button className="quick" onClick={()=>open(p)}><Search/> Vista rápida</button></div><div className="pcopy"><span className="pbrand">{p.brand} · {p.category}</span><h3 onClick={()=>open(p)}>{p.name}</h3><span className={p.stock?"instock":"out"}><PackageCheck/>{p.stock?`${p.stock} disponibles`:"Agotado"}</span><div className="pprice"><b>{gs(p.price)}</b>{p.oldPrice&&<del>{gs(p.oldPrice)}</del>}</div><div className="actions"><button onClick={()=>open(p)}>Ver detalles <ArrowRight/></button><button onClick={()=>add(p)} disabled={!p.stock} aria-label="Agregar al carrito"><ShoppingCart/></button></div></div></article>}

const adminNav=[["Dashboard",LayoutDashboard],["Productos",Package],["Catálogo",Grid2X2],["Marcas",BadgeCheck],["Ofertas",Tag],["Inventario",Warehouse],["Imágenes",ImagePlus]] as const;
function Admin({onExit}:{onExit:()=>void}){
  const [tab,setTab]=useState("Dashboard"); const [showForm,setShowForm]=useState(false);
  const [adminProducts,setAdminProducts]=useState(demoProducts); const [editing,setEditing]=useState<Product|null>(null);
  const reload=async()=>{try{const data=await fetchStoreProducts(true);setAdminProducts(data.length?data:demoProducts)}catch(error){console.error("Admin products:",error)}};
  useEffect(()=>{const timer=setTimeout(reload,0);const changed=()=>reload();window.addEventListener("products-changed",changed);const unsubscribe=subscribeToCatalog(reload);return()=>{clearTimeout(timer);window.removeEventListener("products-changed",changed);unsubscribe()}},[]);
  const openNew=()=>{setEditing(null);setShowForm(true)};
  const edit=(p:Product)=>{setEditing(p);setShowForm(true)};
  const duplicate=async(p:Product)=>{if(!p.dbId)return;const {data,error}=await supabase.rpc("duplicate_product",{source_product_id:p.dbId});if(error){alert(`No se pudo duplicar: ${error.message}`);return}await reload();const copy=(await fetchStoreProducts(true)).find(item=>item.dbId===data);if(copy){setEditing(copy);setShowForm(true)}};
  const remove=async(p:Product)=>{if(!p.dbId||!confirm(`¿Archivar "${p.name}"? Se conservará su historial de inventario.`))return;try{await deleteProduct(p);await reload();window.dispatchEvent(new Event("products-changed"))}catch(error){alert(error instanceof Error?error.message:"No se pudo archivar.")}};
  const metrics=[["Productos",String(adminProducts.length),Package],["Con stock",String(adminProducts.filter(p=>p.stock>0).length),PackageCheck],["Agotados",String(adminProducts.filter(p=>p.stock===0).length),Box],["En oferta",String(adminProducts.filter(p=>p.oldPrice).length),Tag],["Categorías",String(new Set(adminProducts.map(p=>p.category)).size),Grid2X2],["Valor inventario",gs(adminProducts.reduce((s,p)=>s+p.price*p.stock,0)),CircleDollarSign]] as const;
  return <div className="adminShell"><aside><div className="logo"><b>NL</b><span>NextLevel<small>ADMIN</small></span></div>{adminNav.map(([name,Icon])=><button className={tab===name?"active":""} onClick={()=>setTab(name)} key={name}><Icon/>{name}</button>)}<button onClick={onExit}><ArrowLeft/> Cerrar sesión</button></aside><section><div className="adminTop"><div><span>ADMINISTRACIÓN</span><h1>{tab}</h1><p>Gestioná el catálogo y el inventario de la tienda.</p></div><button className="primary newProduct" onClick={openNew}><Plus/> Nuevo producto</button></div>{tab==="Dashboard"?<><div className="metrics">{metrics.map(([label,value,Icon])=><div key={label}><span className="metricIcon"><Icon/></span><div><span>{label}</span><b>{value}</b><small>Actualizado ahora</small></div></div>)}</div><div className="adminPanel critical"><div className="panelHeading"><div><h2>Stock crítico</h2><p>Productos que requieren reposición próximamente.</p></div><button className="secondary" onClick={()=>setTab("Inventario")}>Ver inventario <ArrowRight/></button></div><table><thead><tr><th>Producto</th><th>Stock actual</th><th>Estado</th><th>Precio</th><th></th></tr></thead><tbody>{adminProducts.filter(p=>p.stock<=(p.minimumStock??3)).map(p=><tr key={p.id}><td><div className="tableProd"><img src={p.image} alt=""/><b>{p.name}<small>{p.category}</small></b></div></td><td><b>{p.stock}</b> unidades</td><td><span className="low"><Gauge/> Stock bajo</span></td><td>{gs(p.price)}</td><td><button className="tableIcon" onClick={()=>edit(p)}><Edit3/></button></td></tr>)}</tbody></table></div></>:<ProductTable items={adminProducts} tab={tab} edit={edit} duplicate={duplicate} remove={remove}/>}</section>{showForm&&<ProductForm product={editing} onClose={()=>setShowForm(false)} onSaved={async()=>{setShowForm(false);await reload();window.dispatchEvent(new Event("products-changed"))}}/>}</div>
}

function AdminCategorySelect({categories,value,onChange}:{categories:MainCategory[],value:string,onChange:(value:string)=>void}){
 const [open,setOpen]=useState(false);const root=useRef<HTMLDivElement>(null);
 const options=[{id:"all",name:"Todas las categorías"},...categories];const selectedIndex=Math.max(0,options.findIndex(option=>option.id===value));const selected=options[selectedIndex];
 useEffect(()=>{const close=(event:PointerEvent)=>{if(!root.current?.contains(event.target as Node))setOpen(false)};document.addEventListener("pointerdown",close);return()=>document.removeEventListener("pointerdown",close)},[]);
 const choose=(id:string)=>{onChange(id);setOpen(false)};
 const keyDown=(event:React.KeyboardEvent)=>{if(event.key==="Escape"){setOpen(false);return}if(event.key==="Enter"||event.key===" "){event.preventDefault();setOpen(current=>!current);return}if(event.key==="ArrowDown"||event.key==="ArrowUp"){event.preventDefault();const direction=event.key==="ArrowDown"?1:-1;choose(options[(selectedIndex+direction+options.length)%options.length].id)}};
 return <div className={`adminCategorySelect ${open?"open":""}`} ref={root}>
  <button type="button" className="adminSelectTrigger" aria-haspopup="listbox" aria-expanded={open} onClick={()=>setOpen(current=>!current)} onKeyDown={keyDown}><Grid2X2/><span>{selected.name}</span><ChevronDown className="adminSelectArrow"/></button>
  {open&&<div className="adminSelectMenu" role="listbox" aria-label="Filtrar por categoría principal">{options.map(option=><button type="button" role="option" aria-selected={option.id===value} className={option.id===value?"selected":""} key={option.id} onClick={()=>choose(option.id)}><span>{option.name}</span>{option.id===value&&<Check/>}</button>)}</div>}
 </div>
}

function ProductTable({items,tab,edit,duplicate,remove}:{items:Product[],tab:string,edit:(p:Product)=>void,duplicate:(p:Product)=>void,remove:(p:Product)=>void}){
 const [query,setQuery]=useState("");const [mainCategory,setMainCategory]=useState("all");const [mainCategories,setMainCategories]=useState<MainCategory[]>([]);const [filterOpen,setFilterOpen]=useState(false);const [status,setStatus]=useState("all");const [page,setPage]=useState(1);const size=10;
 useEffect(()=>{let active=true;const reloadCategories=()=>fetchMainCategories().then(data=>{if(active)setMainCategories(data)}).catch(error=>console.error("Admin categories:",error));reloadCategories();const unsubscribe=subscribeToCatalog(reloadCategories);return()=>{active=false;unsubscribe()}},[]);
 const selected=mainCategories.find(category=>category.id===mainCategory);const acceptedCategories=selected?[selected.name,...selected.children]:[];
 const filtered=items.filter(p=>(tab==="Catálogo"?(mainCategory==="all"||acceptedCategories.includes(p.category)):`${p.name} ${p.code||""} ${p.brand} ${p.category}`.toLowerCase().includes(query.toLowerCase()))&&(status==="all"||(status==="active"&&p.isActive!==false)||(status==="inactive"&&p.isActive===false)||(status==="stock"&&p.stock>0)||(status==="out"&&p.stock===0)||(status==="sale"&&!!p.oldPrice)));
 const pages=Math.max(1,Math.ceil(filtered.length/size));const current=Math.min(page,pages);const shown=filtered.slice((current-1)*size,current*size);
 return <div className="adminPanel productTable">
  <div className="panelTools">
   {tab==="Catálogo"?<AdminCategorySelect categories={mainCategories} value={mainCategory} onChange={value=>{setMainCategory(value);setPage(1)}}/>:<label><Search/><input value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} placeholder={`Buscar en ${tab.toLowerCase()}...`}/></label>}
   <button className={`secondary filterToggle ${filterOpen?"active":""}`} aria-expanded={filterOpen} aria-controls="admin-product-filters" onClick={()=>setFilterOpen(x=>!x)}><SlidersHorizontal/> Filtros</button>
  </div>
  {filterOpen&&<div className="adminFiltersPanel" id="admin-product-filters"><label><span>Estado e inventario</span><div className="selectWrap"><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}} aria-label="Filtrar productos por estado"><option value="all">Todos los estados</option><option value="active">Activos</option><option value="inactive">Inactivos</option><option value="stock">Con stock</option><option value="out">Agotados</option><option value="sale">En oferta</option></select><ChevronDown/></div></label><button className="clear bordered" onClick={()=>{setStatus("all");setMainCategory("all");setQuery("");setPage(1)}}><X/> Limpiar filtros</button></div>}
  <div className="tableScroll"><table><thead><tr><th>Producto</th><th>Categoría</th><th>Marca</th><th>Stock</th><th>Precio</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{shown.map(p=><tr key={p.id}><td><div className="tableProd"><img src={p.image} alt=""/><b>{p.name}<small>{p.code||`NL-${String(p.id).padStart(4,"0")}`}</small></b></div></td><td>{p.category}</td><td>{p.brand}</td><td><b>{p.stock}</b></td><td><b>{gs(p.price)}</b>{p.oldPrice&&<small><del>{gs(p.oldPrice)}</del></small>}</td><td><span className={p.isActive===false?"low":"ok"}>{p.isActive===false?<X/>:<Check/>} {p.isActive===false?"Inactivo":"Activo"}</span></td><td><div className="tableActions"><button onClick={()=>edit(p)} title="Editar producto"><Edit3/></button><button onClick={()=>duplicate(p)} title="Duplicar producto"><Copy/></button><button onClick={()=>remove(p)} className="danger" title="Archivar producto"><Trash2/></button></div></td></tr>)}</tbody></table>{!shown.length&&<div className="empty"><Search/><b>No hay productos para este filtro</b></div>}</div>
  <div className="pagination"><span>Mostrando {shown.length?`${(current-1)*size+1}–${(current-1)*size+shown.length}`:"0"} de {filtered.length} productos</span><div><button disabled={current===1} onClick={()=>setPage(p=>p-1)}><ChevronLeft/></button>{Array.from({length:pages},(_,i)=><button key={i} className={current===i+1?"active":""} onClick={()=>setPage(i+1)}>{i+1}</button>)}<button disabled={current===pages} onClick={()=>setPage(p=>p+1)}><ChevronRight/></button></div></div>
 </div>
}

type Preview={id:string,url:string,name:string,main:boolean,file?:File,storagePath?:string};
function ProductForm({product,onClose,onSaved}:{product:Product|null,onClose:()=>void,onSaved:()=>void}){
 const [previews,setPreviews]=useState<Preview[]>(product?(product.images?.map(x=>({id:x.id,url:x.url,name:x.storagePath.split("/").pop()||"Imagen",main:x.isPrimary,storagePath:x.storagePath}))||[{id:"existing",url:product.image,name:"Imagen actual",main:true}]):[]);
 const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 const [defaultCode]=useState(()=>`NL-${Date.now().toString().slice(-6)}`);
 const addFiles=(files:FileList|File[])=>{const incoming=Array.from(files).filter(f=>f.type.startsWith("image/")).map((f,i)=>({id:`${Date.now()}-${i}`,url:URL.createObjectURL(f),name:f.name,main:previews.length===0&&i===0,file:f}));setPreviews(x=>[...x,...incoming])};
 const move=(index:number,dir:number)=>setPreviews(x=>{const n=[...x],target=index+dir;if(target<0||target>=n.length)return x;[n[index],n[target]]=[n[target],n[index]];return n});
 const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setError("");const fd=new FormData(e.currentTarget);const input:ProductInput={name:String(fd.get("name")),code:String(fd.get("code")),brand:String(fd.get("brand")),category:String(fd.get("category")),model:String(fd.get("model")),normalPrice:Number(fd.get("normalPrice")),salePrice:fd.get("salePrice")?Number(fd.get("salePrice")):null,stock:Number(fd.get("stock")),minimumStock:Number(fd.get("minimumStock")),description:String(fd.get("description")),warranty:String(fd.get("warranty")),isActive:fd.get("isActive")==="on",isFeatured:fd.get("isFeatured")==="on",isNew:fd.get("isNew")==="on",isOnSale:fd.get("isOnSale")==="on",previews};try{await saveProduct(product,input);onSaved()}catch(err){setError(err instanceof Error?err.message:"No se pudo guardar.");setBusy(false)}};
 return <div className="modalWrap"><form className="productModal" onSubmit={submit}><div className="formHeader"><div><span className="eyebrow">GESTIÓN DE CATÁLOGO</span><h2>{product?"Editar producto":"Nuevo producto"}</h2><p>Completá la información que se mostrará en la tienda.</p></div><button type="button" className="iconBtn" onClick={onClose}><X/></button></div><div className="formBody">
 <FormSection icon={<Package/>} title="Información básica"><div className="formGrid"><label className="span2">Nombre del producto<input name="name" required defaultValue={product?.name||""} placeholder="Ej. Notebook ASUS TUF Gaming A15"/></label><label>Código<input name="code" required defaultValue={product?.code||defaultCode}/></label><label>Marca<input name="brand" required defaultValue={product?.brand||"NextLevel"}/></label><label>Categoría<select name="category" defaultValue={product?.category}>{categories.slice(1).map(c=><option key={c}>{c}</option>)}</select></label><label>Modelo<input name="model" defaultValue={product?.model||""} placeholder="Modelo o referencia"/></label></div></FormSection>
 <FormSection icon={<CreditCard/>} title="Precios"><div className="formGrid"><label>Precio normal (Gs.)<input name="normalPrice" min="0" required type="number" defaultValue={product?.oldPrice||product?.price||1000000}/></label><label>Precio promocional (Gs.)<input name="salePrice" min="0" type="number" defaultValue={product?.oldPrice?product.price:""}/></label></div></FormSection>
 <FormSection icon={<Warehouse/>} title="Inventario"><div className="formGrid"><label>Stock disponible<input name="stock" min="0" required type="number" defaultValue={product?.stock??10}/></label><label>Alerta de stock mínimo<input name="minimumStock" min="0" required type="number" defaultValue={product?.minimumStock??3}/></label></div></FormSection>
 <FormSection icon={<Edit3/>} title="Descripción"><div className="formGrid"><label className="span2">Descripción completa<textarea name="description" required defaultValue={product?.description||""} placeholder="Características, beneficios y detalles del producto."/></label><label className="span2">Garantía<input name="warranty" defaultValue={product?.warranty||"12 meses"}/></label></div></FormSection>
 <FormSection icon={<ImagePlus/>} title="Imágenes del producto"><ImageManager previews={previews} setPreviews={setPreviews} addFiles={addFiles} move={move}/></FormSection>
 <FormSection icon={<SlidersHorizontal/>} title="Estado y visibilidad"><div className="switchGrid"><Switch name="isActive" label="Producto activo" description="Visible y disponible en la tienda" checked={product?.isActive!==false}/><Switch name="isFeatured" label="Producto destacado" description="Aparece en secciones principales" checked={product?.featured}/><Switch name="isNew" label="Producto nuevo" description="Muestra la etiqueta Nuevo" checked={product?.isNew}/><Switch name="isOnSale" label="Producto en oferta" description="Activa el precio promocional" checked={!!product?.oldPrice}/></div></FormSection></div>
 {error&&<p className="loginError">{error}</p>}<div className="formActions"><button type="button" className="secondary" onClick={onClose}>Cancelar</button><button disabled={busy} className="primary"><Check/> {busy?"Guardando...":"Guardar producto"}</button></div></form></div>
}
function FormSection({icon,title,children}:{icon:React.ReactNode,title:string,children:React.ReactNode}){return <section className="formSection"><header><span>{icon}</span><h3>{title}</h3></header>{children}</section>}
function Switch({name,label,description,checked=false}:{name:string,label:string,description:string,checked?:boolean}){const [on,setOn]=useState(!!checked);return <label className="switchRow"><input name={name} type="checkbox" checked={on} onChange={e=>setOn(e.target.checked)} hidden/><span><b>{label}</b><small>{description}</small></span><i className={on?"on":""}><em/></i></label>}
function ImageManager({previews,setPreviews,addFiles,move}:{previews:Preview[],setPreviews:React.Dispatch<React.SetStateAction<Preview[]>>,addFiles:(f:FileList|File[])=>void,move:(i:number,d:number)=>void}){return <div><label className="dropZone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();addFiles(e.dataTransfer.files)}}><UploadCloud/><b>Arrastrá tus imágenes aquí</b><span>o hacé clic para seleccionarlas desde tu computadora</span><small>JPG, PNG o WebP · máximo recomendado 2 MB</small><input type="file" accept="image/*" multiple onChange={e=>e.target.files&&addFiles(e.target.files)}/></label>{previews.length>0&&<div className="imagePreviews">{previews.map((img,i)=><article key={img.id} className={img.main?"mainImage":""}><img src={img.url} alt={img.name}/><div><span>{img.main?"Imagen principal":img.name}</span><div><button type="button" onClick={()=>move(i,-1)} disabled={i===0}><ChevronLeft/></button><button type="button" onClick={()=>move(i,1)} disabled={i===previews.length-1}><ChevronRight/></button><button type="button" onClick={()=>setPreviews(x=>x.map(v=>({...v,main:v.id===img.id})))} title="Elegir como principal"><BadgeCheck/></button><button type="button" className="danger" onClick={()=>setPreviews(x=>x.filter(v=>v.id!==img.id))}><Trash2/></button></div></div></article>)}</div>}</div>}
