do $$
declare
  catalog jsonb := $catalog$
[
{"code":"NL-0016","name":"PC Gamer Ryzen 5 7600 RTX 4060 Ti","slug":"pc-gamer-ryzen-5-7600-rtx-4060-ti","model":"NL-R57600-4060TI","brand":"NextLevel","brand_slug":"nextlevel","category":"pc-gamer","price":10490000,"sale":9990000,"stock":6,"featured":true,"new":false,"offer":true,"description":"Equipo equilibrado para gaming competitivo en 1080p y 1440p.","specs":{"Procesador":"AMD Ryzen 5 7600","Gráficos":"GeForce RTX 4060 Ti 8 GB","Memoria":"32 GB DDR5","Almacenamiento":"SSD NVMe 1 TB"}},
{"code":"NL-0017","name":"PC Gamer Core i5-14400F RTX 4060","slug":"pc-gamer-core-i5-14400f-rtx-4060","model":"NL-I514400F-4060","brand":"NextLevel","brand_slug":"nextlevel","category":"pc-gamer","price":9390000,"sale":null,"stock":8,"featured":false,"new":true,"offer":false,"description":"PC gamer eficiente para alta frecuencia de cuadros y tareas diarias.","specs":{"Procesador":"Intel Core i5-14400F","Gráficos":"GeForce RTX 4060 8 GB","Memoria":"16 GB DDR5","Almacenamiento":"SSD NVMe 1 TB"}},
{"code":"NL-0018","name":"PC Gamer Ryzen 7 7700 RX 7800 XT","slug":"pc-gamer-ryzen-7-7700-rx-7800-xt","model":"NL-R77700-7800XT","brand":"NextLevel","brand_slug":"nextlevel","category":"pc-gamer","price":13990000,"sale":null,"stock":4,"featured":true,"new":false,"offer":false,"description":"Potencia para jugar en 1440p, transmitir y crear contenido.","specs":{"Procesador":"AMD Ryzen 7 7700","Gráficos":"Radeon RX 7800 XT 16 GB","Memoria":"32 GB DDR5","Almacenamiento":"SSD NVMe 2 TB"}},
{"code":"NL-0019","name":"PC Gamer Core i7-14700F RTX 4070 Super","slug":"pc-gamer-core-i7-14700f-rtx-4070-super","model":"NL-I714700F-4070S","brand":"NextLevel","brand_slug":"nextlevel","category":"pc-gamer","price":17490000,"sale":16490000,"stock":3,"featured":true,"new":false,"offer":true,"description":"Configuración avanzada para gaming 1440p y producción profesional.","specs":{"Procesador":"Intel Core i7-14700F","Gráficos":"GeForce RTX 4070 Super 12 GB","Memoria":"32 GB DDR5","Almacenamiento":"SSD NVMe 2 TB"}},
{"code":"NL-0020","name":"PC Gamer Ryzen 7 7800X3D RTX 4080 Super","slug":"pc-gamer-ryzen-7-7800x3d-rtx-4080-super","model":"NL-R77800X3D-4080S","brand":"NextLevel","brand_slug":"nextlevel","category":"pc-gamer","price":25990000,"sale":null,"stock":2,"featured":true,"new":true,"offer":false,"description":"Sistema entusiasta preparado para gaming 4K y cargas exigentes.","specs":{"Procesador":"AMD Ryzen 7 7800X3D","Gráficos":"GeForce RTX 4080 Super 16 GB","Memoria":"64 GB DDR5","Almacenamiento":"SSD NVMe 2 TB"}},
{"code":"NL-0021","name":"PC Gamer Ryzen 5 5600G Essential","slug":"pc-gamer-ryzen-5-5600g-essential","model":"NL-R55600G-ESS","brand":"NextLevel","brand_slug":"nextlevel","category":"pc-gamer","price":4290000,"sale":3990000,"stock":10,"featured":false,"new":false,"offer":true,"description":"Equipo accesible y actualizable para esports y uso cotidiano.","specs":{"Procesador":"AMD Ryzen 5 5600G","Gráficos":"Radeon integrada","Memoria":"16 GB DDR4","Almacenamiento":"SSD NVMe 500 GB"}},
{"code":"NL-0022","name":"Notebook Acer Aspire 5 A515","slug":"notebook-acer-aspire-5-a515","model":"A515","brand":"Acer","brand_slug":"acer","category":"notebooks","price":5290000,"sale":null,"stock":9,"featured":false,"new":false,"offer":false,"description":"Notebook versátil para productividad, estudio y entretenimiento.","specs":{"Pantalla":"15,6 pulgadas Full HD","Procesador":"Intel Core i5","Memoria":"16 GB","Almacenamiento":"SSD 512 GB"}},
{"code":"NL-0023","name":"Notebook Lenovo LOQ 15IRX9","slug":"notebook-lenovo-loq-15irx9","model":"15IRX9","brand":"Lenovo","brand_slug":"lenovo","category":"notebooks","price":9490000,"sale":8990000,"stock":5,"featured":true,"new":false,"offer":true,"description":"Notebook gamer robusta con refrigeración eficiente y pantalla rápida.","specs":{"Pantalla":"15,6 pulgadas 144 Hz","Procesador":"Intel Core i7","Gráficos":"GeForce RTX 4060","Memoria":"16 GB DDR5"}},
{"code":"NL-0024","name":"Notebook ASUS Vivobook 16 X1605","slug":"notebook-asus-vivobook-16-x1605","model":"X1605","brand":"ASUS","brand_slug":"asus","category":"notebooks","price":5990000,"sale":null,"stock":7,"featured":false,"new":true,"offer":false,"description":"Pantalla amplia y diseño liviano para trabajo y estudio.","specs":{"Pantalla":"16 pulgadas WUXGA","Procesador":"Intel Core i5","Memoria":"16 GB","Almacenamiento":"SSD 512 GB"}},
{"code":"NL-0025","name":"Notebook HP Victus 15 Gaming","slug":"notebook-hp-victus-15-gaming","model":"Victus 15","brand":"HP","brand_slug":"hp","category":"notebooks","price":8790000,"sale":8290000,"stock":4,"featured":false,"new":false,"offer":true,"description":"Rendimiento gamer equilibrado en un chasis sobrio y resistente.","specs":{"Pantalla":"15,6 pulgadas 144 Hz","Procesador":"Intel Core i5","Gráficos":"GeForce RTX 4050","Memoria":"16 GB DDR5"}},
{"code":"NL-0026","name":"Notebook MSI Katana 15 B13V","slug":"notebook-msi-katana-15-b13v","model":"Katana 15 B13V","brand":"MSI","brand_slug":"msi","category":"notebooks","price":11990000,"sale":null,"stock":3,"featured":true,"new":true,"offer":false,"description":"Notebook gamer de alto desempeño con teclado RGB y gráficos dedicados.","specs":{"Pantalla":"15,6 pulgadas 144 Hz","Procesador":"Intel Core i7","Gráficos":"GeForce RTX 4060","Memoria":"16 GB DDR5"}},
{"code":"NL-0027","name":"Notebook Dell Inspiron 14 5440","slug":"notebook-dell-inspiron-14-5440","model":"Inspiron 5440","brand":"Dell","brand_slug":"dell","category":"notebooks","price":6490000,"sale":null,"stock":8,"featured":false,"new":false,"offer":false,"description":"Notebook compacta para productividad móvil y videollamadas.","specs":{"Pantalla":"14 pulgadas Full HD+","Procesador":"Intel Core 5","Memoria":"16 GB","Almacenamiento":"SSD 512 GB"}},
{"code":"NL-0028","name":"Apple MacBook Air 13 M3","slug":"apple-macbook-air-13-m3","model":"MacBook Air M3 13","brand":"Apple","brand_slug":"apple","category":"notebooks","price":10990000,"sale":10490000,"stock":5,"featured":true,"new":false,"offer":true,"description":"Notebook ultraliviana con gran autonomía y rendimiento silencioso.","specs":{"Pantalla":"13,6 pulgadas Liquid Retina","Procesador":"Apple M3","Memoria":"8 GB unificada","Almacenamiento":"SSD 256 GB"}},
{"code":"NL-0029","name":"Gigabyte GeForce RTX 4060 Windforce OC 8 GB","slug":"gigabyte-geforce-rtx-4060-windforce-oc-8gb","model":"RTX 4060 WINDFORCE OC","brand":"Gigabyte","brand_slug":"gigabyte","category":"placas-de-video","price":3590000,"sale":null,"stock":7,"featured":false,"new":false,"offer":false,"description":"GPU compacta y eficiente para gaming moderno en 1080p.","specs":{"Memoria":"8 GB GDDR6","Interfaz":"PCI Express 4.0","Refrigeración":"Doble ventilador","Salidas":"HDMI y DisplayPort"}},
{"code":"NL-0030","name":"MSI GeForce RTX 4060 Ti Ventus 2X 8 GB","slug":"msi-geforce-rtx-4060-ti-ventus-2x-8gb","model":"RTX 4060 Ti VENTUS 2X","brand":"MSI","brand_slug":"msi","category":"placas-de-video","price":5190000,"sale":4890000,"stock":5,"featured":false,"new":false,"offer":true,"description":"Gráficos fluidos en 1080p y 1440p con diseño de doble ventilador.","specs":{"Memoria":"8 GB GDDR6","Interfaz":"PCI Express 4.0","Refrigeración":"Ventus 2X","Tecnología":"Ray tracing y DLSS"}},
{"code":"NL-0031","name":"ASUS TUF GeForce RTX 4070 Ti Super 16 GB","slug":"asus-tuf-geforce-rtx-4070-ti-super-16gb","model":"TUF RTX 4070 Ti SUPER","brand":"ASUS","brand_slug":"asus","category":"placas-de-video","price":9990000,"sale":null,"stock":2,"featured":true,"new":true,"offer":false,"description":"GPU premium para jugar en 1440p y 4K con refrigeración reforzada.","specs":{"Memoria":"16 GB GDDR6X","Interfaz":"PCI Express 4.0","Refrigeración":"Triple ventilador","Tecnología":"Ray tracing y DLSS"}},
{"code":"NL-0032","name":"Sapphire Pulse Radeon RX 7600 8 GB","slug":"sapphire-pulse-radeon-rx-7600-8gb","model":"PULSE RX 7600","brand":"Sapphire","brand_slug":"sapphire","category":"placas-de-video","price":2990000,"sale":2790000,"stock":8,"featured":false,"new":false,"offer":true,"description":"Opción eficiente para gaming competitivo en resolución Full HD.","specs":{"Memoria":"8 GB GDDR6","Interfaz":"PCI Express 4.0","Refrigeración":"Doble ventilador","Tecnología":"AMD FidelityFX"}},
{"code":"NL-0033","name":"Sapphire Nitro+ Radeon RX 7800 XT 16 GB","slug":"sapphire-nitro-plus-radeon-rx-7800-xt-16gb","model":"NITRO+ RX 7800 XT","brand":"Sapphire","brand_slug":"sapphire","category":"placas-de-video","price":6490000,"sale":null,"stock":4,"featured":true,"new":false,"offer":false,"description":"Alto rendimiento en 1440p con gran capacidad de memoria gráfica.","specs":{"Memoria":"16 GB GDDR6","Interfaz":"PCI Express 4.0","Refrigeración":"Triple ventilador","Tecnología":"AMD FidelityFX"}},
{"code":"NL-0034","name":"Intel Arc B580 Limited Edition 12 GB","slug":"intel-arc-b580-limited-edition-12gb","model":"Arc B580 Limited Edition","brand":"Intel","brand_slug":"intel","category":"placas-de-video","price":3290000,"sale":null,"stock":6,"featured":false,"new":true,"offer":false,"description":"Gráficos modernos con 12 GB de memoria y aceleración multimedia.","specs":{"Memoria":"12 GB GDDR6","Interfaz":"PCI Express 4.0","Refrigeración":"Doble ventilador","Tecnología":"XeSS"}},
{"code":"NL-0035","name":"PlayStation 5 Pro 2 TB","slug":"playstation-5-pro-2tb","model":"PS5 Pro","brand":"Sony","brand_slug":"sony","category":"playstation","price":8490000,"sale":null,"stock":3,"featured":true,"new":true,"offer":false,"description":"Consola de alto rendimiento con almacenamiento amplio y gráficos mejorados.","specs":{"Almacenamiento":"SSD 2 TB","Resolución":"Hasta 4K","Conectividad":"Wi-Fi y Ethernet","Control":"DualSense incluido"}},
{"code":"NL-0036","name":"Xbox Series S 1 TB Carbon Black","slug":"xbox-series-s-1tb-carbon-black","model":"Series S 1 TB","brand":"Microsoft","brand_slug":"microsoft","category":"xbox","price":3990000,"sale":3690000,"stock":6,"featured":false,"new":false,"offer":true,"description":"Consola digital compacta con almacenamiento de 1 TB.","specs":{"Almacenamiento":"SSD 1 TB","Resolución":"Hasta 1440p","Formato":"Edición digital","Control":"Wireless Controller incluido"}},
{"code":"NL-0037","name":"Nintendo Switch Lite Turquesa","slug":"nintendo-switch-lite-turquesa","model":"Switch Lite","brand":"Nintendo","brand_slug":"nintendo","category":"nintendo","price":1990000,"sale":null,"stock":10,"featured":false,"new":false,"offer":false,"description":"Consola portátil ligera con controles integrados.","specs":{"Pantalla":"5,5 pulgadas","Almacenamiento":"32 GB","Modo":"Portátil","Color":"Turquesa"}},
{"code":"NL-0038","name":"Nintendo Switch 2","slug":"nintendo-switch-2","model":"Switch 2","brand":"Nintendo","brand_slug":"nintendo","category":"nintendo","price":4990000,"sale":null,"stock":5,"featured":true,"new":true,"offer":false,"description":"Consola híbrida de nueva generación para jugar en casa o en movimiento.","specs":{"Pantalla":"7,9 pulgadas","Almacenamiento":"256 GB","Modo":"TV y portátil","Conectividad":"Wi-Fi 6"}},
{"code":"NL-0039","name":"Monitor LG UltraGear 24GS60F 24 pulgadas 180 Hz","slug":"monitor-lg-ultragear-24gs60f-24-180hz","model":"24GS60F","brand":"LG","brand_slug":"lg","category":"monitores","price":1790000,"sale":1590000,"stock":12,"featured":false,"new":false,"offer":true,"description":"Monitor rápido y compacto para esports y gaming competitivo.","specs":{"Panel":"IPS 24 pulgadas","Resolución":"1920 x 1080","Frecuencia":"180 Hz","Respuesta":"1 ms"}},
{"code":"NL-0040","name":"Monitor Samsung Odyssey G5 27 pulgadas QHD","slug":"monitor-samsung-odyssey-g5-27-qhd","model":"Odyssey G5 27","brand":"Samsung","brand_slug":"samsung","category":"monitores","price":2990000,"sale":null,"stock":7,"featured":false,"new":false,"offer":false,"description":"Pantalla curva QHD inmersiva para gaming y entretenimiento.","specs":{"Panel":"VA curvo 27 pulgadas","Resolución":"2560 x 1440","Frecuencia":"165 Hz","Sincronización":"Adaptive Sync"}},
{"code":"NL-0041","name":"Monitor ASUS TUF VG27AQ3A 27 pulgadas 180 Hz","slug":"monitor-asus-tuf-vg27aq3a-27-180hz","model":"VG27AQ3A","brand":"ASUS","brand_slug":"asus","category":"monitores","price":3490000,"sale":3290000,"stock":6,"featured":true,"new":false,"offer":true,"description":"Monitor QHD de alta frecuencia con colores precisos y baja latencia.","specs":{"Panel":"Fast IPS 27 pulgadas","Resolución":"2560 x 1440","Frecuencia":"180 Hz","Respuesta":"1 ms"}},
{"code":"NL-0042","name":"Monitor MSI MAG 274QRF QD E2 27 pulgadas","slug":"monitor-msi-mag-274qrf-qd-e2-27","model":"MAG 274QRF QD E2","brand":"MSI","brand_slug":"msi","category":"monitores","price":4290000,"sale":null,"stock":4,"featured":true,"new":true,"offer":false,"description":"Panel QHD Quantum Dot con amplia gama de color y gran fluidez.","specs":{"Panel":"Rapid IPS Quantum Dot","Resolución":"2560 x 1440","Frecuencia":"180 Hz","Respuesta":"1 ms"}},
{"code":"NL-0043","name":"Monitor AOC 24G4 24 pulgadas 180 Hz","slug":"monitor-aoc-24g4-24-180hz","model":"24G4","brand":"AOC","brand_slug":"aoc","category":"monitores","price":1690000,"sale":null,"stock":11,"featured":false,"new":false,"offer":false,"description":"Monitor esports accesible con panel IPS y soporte ajustable.","specs":{"Panel":"Fast IPS 24 pulgadas","Resolución":"1920 x 1080","Frecuencia":"180 Hz","Respuesta":"1 ms"}},
{"code":"NL-0044","name":"Monitor Gigabyte M32U 32 pulgadas 4K 144 Hz","slug":"monitor-gigabyte-m32u-32-4k-144hz","model":"M32U","brand":"Gigabyte","brand_slug":"gigabyte","category":"monitores","price":7490000,"sale":6990000,"stock":3,"featured":true,"new":false,"offer":true,"description":"Monitor 4K de gran formato para gaming, consolas y productividad.","specs":{"Panel":"IPS 32 pulgadas","Resolución":"3840 x 2160","Frecuencia":"144 Hz","Conectividad":"HDMI 2.1 y USB-C"}},
{"code":"NL-0045","name":"Mouse Logitech G Pro X Superlight 2","slug":"mouse-logitech-g-pro-x-superlight-2","model":"G Pro X Superlight 2","brand":"Logitech","brand_slug":"logitech","category":"mouse","price":1190000,"sale":null,"stock":14,"featured":true,"new":false,"offer":false,"description":"Mouse inalámbrico ultraliviano diseñado para competición.","specs":{"Sensor":"Óptico de alta precisión","Peso":"60 g","Conexión":"Inalámbrica","Batería":"Hasta 95 horas"}},
{"code":"NL-0046","name":"Teclado Razer BlackWidow V4 X","slug":"teclado-razer-blackwidow-v4-x","model":"BlackWidow V4 X","brand":"Razer","brand_slug":"razer","category":"teclados","price":1090000,"sale":999000,"stock":9,"featured":false,"new":false,"offer":true,"description":"Teclado mecánico completo con macros y retroiluminación configurable.","specs":{"Formato":"Completo","Switches":"Mecánicos","Iluminación":"RGB","Conexión":"USB"}},
{"code":"NL-0047","name":"Auriculares SteelSeries Arctis Nova 5 Wireless","slug":"auriculares-steelseries-arctis-nova-5-wireless","model":"Arctis Nova 5 Wireless","brand":"SteelSeries","brand_slug":"steelseries","category":"auriculares","price":1390000,"sale":null,"stock":8,"featured":false,"new":true,"offer":false,"description":"Auriculares inalámbricos cómodos con audio espacial y micrófono retráctil.","specs":{"Conexión":"2,4 GHz y Bluetooth","Batería":"Hasta 60 horas","Micrófono":"Retráctil","Compatibilidad":"PC y consolas"}},
{"code":"NL-0048","name":"Control inalámbrico DualSense Midnight Black","slug":"control-inalambrico-dualsense-midnight-black","model":"DualSense Midnight Black","brand":"Sony","brand_slug":"sony","category":"accesorios","price":699000,"sale":649000,"stock":16,"featured":false,"new":false,"offer":true,"description":"Control inalámbrico con respuesta háptica y gatillos adaptativos.","specs":{"Conexión":"Bluetooth y USB-C","Respuesta":"Háptica","Gatillos":"Adaptativos","Color":"Midnight Black"}},
{"code":"NL-0049","name":"Control inalámbrico Xbox Carbon Black","slug":"control-inalambrico-xbox-carbon-black","model":"Xbox Wireless Controller","brand":"Microsoft","brand_slug":"microsoft","category":"accesorios","price":599000,"sale":null,"stock":18,"featured":false,"new":false,"offer":false,"description":"Control ergonómico compatible con Xbox, PC y dispositivos móviles.","specs":{"Conexión":"Xbox Wireless y Bluetooth","Alimentación":"Pilas AA","Compatibilidad":"Xbox y PC","Color":"Carbon Black"}},
{"code":"NL-0050","name":"Volante Logitech G923 TrueForce","slug":"volante-logitech-g923-trueforce","model":"G923","brand":"Logitech","brand_slug":"logitech","category":"accesorios","price":3290000,"sale":2990000,"stock":5,"featured":true,"new":false,"offer":true,"description":"Volante de simulación con force feedback y pedalera de tres pedales.","specs":{"Rotación":"900 grados","Respuesta":"TrueForce","Pedales":"Acelerador, freno y embrague","Material":"Cuero y metal"}},
{"code":"NL-0051","name":"Elgato Stream Deck MK.2","slug":"elgato-stream-deck-mk2","model":"Stream Deck MK.2","brand":"Elgato","brand_slug":"elgato","category":"accesorios","price":1390000,"sale":null,"stock":7,"featured":false,"new":true,"offer":false,"description":"Panel de control con teclas LCD para streaming y productividad.","specs":{"Teclas":"15 LCD configurables","Conexión":"USB-C","Soporte":"Ajustable","Compatibilidad":"Windows y macOS"}}
]
$catalog$::jsonb;
begin
  insert into public.brands(name,slug,is_active)
  select distinct x->>'brand',x->>'brand_slug',true from jsonb_array_elements(catalog) x
  on conflict(slug) do update set name=excluded.name,is_active=true;

  insert into public.products(name,code,slug,description,model,brand_id,category_id,price,sale_price,stock,minimum_stock,is_active,is_featured,is_new,is_on_sale,warranty)
  select x->>'name',x->>'code',x->>'slug',x->>'description',x->>'model',
    (select id from public.brands where slug=x->>'brand_slug'),
    (select id from public.categories where slug=x->>'category'),
    (x->>'price')::numeric,nullif(x->>'sale','')::numeric,(x->>'stock')::int,3,true,
    (x->>'featured')::boolean,(x->>'new')::boolean,(x->>'offer')::boolean,'12 meses'
  from jsonb_array_elements(catalog) x
  on conflict(code) do nothing;

  insert into public.product_images(product_id,storage_path,public_url,alt_text,sort_order,is_primary)
  select p.id,'catalog-2026-07/'||(x->>'code')||'.webp',
    'https://uvbmavhpozyovzupuwwt.supabase.co/storage/v1/object/public/products/catalog-2026-07/'||(x->>'code')||'.webp',
    x->>'name',0,true
  from jsonb_array_elements(catalog) x join public.products p on p.code=x->>'code'
  on conflict(product_id,storage_path) do nothing;

  insert into public.product_specs(product_id,name,value,sort_order)
  select p.id,s.key,s.value,row_number() over(partition by p.id order by s.key)::int
  from jsonb_array_elements(catalog) x
  join public.products p on p.code=x->>'code'
  cross join lateral jsonb_each_text(x->'specs') s
  where not exists(select 1 from public.product_specs ps where ps.product_id=p.id and ps.name=s.key);
end $$;
